version: '3.7'
services:
  web:
    image: tomcat
    container_name: tomcat_server
    volumes:
      - ../target/spring-mvc-one.war:/usr/local/tomcat/webapps/spring-mvc-one.war
    ports:
      - '8082:8080'
